/**
 * 1-Glance product identity for the Help Center.
 * Assets come from ../public/brand (committed frontend product files).
 */
const fs = require('fs');
const path = require('path');

const FRONTEND_ROOT = path.resolve(__dirname, '..', '..');

const PRODUCT = {
  slug: '1glance',
  name: '1-Glance',
  shortName: '1G',
  tagline: 'The Digital Curator for Your Document Intelligence Platform',
  copyright: 'Alonix Intelligence Systems',
  supportEmail: 'support@1glance.ai',
  salesEmail: 'sales@1glance.ai',
  websiteUrl: 'https://1glance.ai',
  privacyUrl: 'https://1glance.ai/privacy',
  termsUrl: 'https://1glance.ai/terms',
  primaryLight: '#005ac1',
  primaryDark: '#ADC6FF',
};

function pickFaviconFile(files) {
  const priority = ['.png', '.ico', '.webp', '.svg'];
  for (const ext of priority) {
    const match = files.find((f) => f.startsWith('favicon.') && f.endsWith(ext));
    if (match) return match;
  }
  return files.find((f) => f.startsWith('favicon.'));
}

function copyDir(src, dest) {
  if (!fs.existsSync(src)) {
    throw new Error(`Missing product assets at ${src}`);
  }
  fs.mkdirSync(dest, {recursive: true});
  for (const file of fs.readdirSync(src)) {
    if (file === '.DS_Store') continue;
    fs.copyFileSync(path.join(src, file), path.join(dest, file));
  }
}

function syncBrandAssets(destDir) {
  const src = path.join(FRONTEND_ROOT, 'public', 'brand');
  if (fs.existsSync(destDir)) {
    fs.rmSync(destDir, {recursive: true, force: true});
  }
  copyDir(src, destDir);
}

function resolveLogoPath(brandStaticDir) {
  const candidates = ['logo.png', 'logo.svg', 'logo.webp', 'logo-icon.png'];
  for (const file of candidates) {
    if (fs.existsSync(path.join(brandStaticDir, file))) return `brand/${file}`;
  }
  throw new Error(`Missing logo in ${brandStaticDir}`);
}

function resolveFaviconPath(brandStaticDir) {
  const files = fs.existsSync(brandStaticDir) ? fs.readdirSync(brandStaticDir) : [];
  const favicon = pickFaviconFile(files);
  if (!favicon) throw new Error(`Missing favicon in ${brandStaticDir}`);
  return `brand/${favicon}`;
}

function hexToRgb(hex) {
  const normalized = hex.replace('#', '');
  const full =
    normalized.length === 3
      ? normalized
          .split('')
          .map((c) => c + c)
          .join('')
      : normalized;
  const num = parseInt(full, 16);
  return {
    r: (num >> 16) & 255,
    g: (num >> 8) & 255,
    b: num & 255,
  };
}

function shadeHex(hex, amount) {
  const {r, g, b} = hexToRgb(hex);
  const channels = [r, g, b].map((channel) => {
    if (amount >= 0) {
      return Math.max(0, Math.min(255, Math.round(channel + (255 - channel) * amount)));
    }
    return Math.max(0, Math.min(255, Math.round(channel * (1 - Math.abs(amount)))));
  });
  return `#${channels.map((c) => c.toString(16).padStart(2, '0')).join('')}`;
}

function buildThemeCss(brand) {
  const light = brand.primaryLight;
  const dark = brand.primaryDark;
  return `/* Generated by scripts/sync-brand.js — do not edit */
:root {
  --ifm-color-primary: ${light};
  --ifm-color-primary-dark: ${shadeHex(light, -0.12)};
  --ifm-color-primary-darker: ${shadeHex(light, -0.2)};
  --ifm-color-primary-darkest: ${shadeHex(light, -0.32)};
  --ifm-color-primary-light: ${shadeHex(light, 0.12)};
  --ifm-color-primary-lighter: ${shadeHex(light, 0.24)};
  --ifm-color-primary-lightest: ${shadeHex(light, 0.36)};
  --docusaurus-highlighted-code-line-bg: rgba(${hexToRgb(light).r}, ${hexToRgb(light).g}, ${hexToRgb(light).b}, 0.1);
}

[data-theme='dark'] {
  --ifm-color-primary: ${dark};
  --ifm-color-primary-dark: ${shadeHex(dark, -0.1)};
  --ifm-color-primary-darker: ${shadeHex(dark, -0.18)};
  --ifm-color-primary-darkest: ${shadeHex(dark, -0.28)};
  --ifm-color-primary-light: ${shadeHex(dark, 0.1)};
  --ifm-color-primary-lighter: ${shadeHex(dark, 0.2)};
  --ifm-color-primary-lightest: ${shadeHex(dark, 0.3)};
}

.hero--primary {
  --ifm-hero-background-color: linear-gradient(
    135deg,
    ${shadeHex(light, -0.32)} 0%,
    ${light} 50%,
    ${shadeHex(light, 0.12)} 100%
  );
  --ifm-hero-text-color: #ffffff;
}
`;
}

function toBrandConfig(brandStaticDir) {
  return {
    ...PRODUCT,
    logoPath: resolveLogoPath(brandStaticDir),
    faviconPath: resolveFaviconPath(brandStaticDir),
    helpCenterTitle: `${PRODUCT.name} Help Center`,
    navbarTitle: `${PRODUCT.shortName} Help`,
  };
}

function applyBrandTokens(text, brand) {
  return text
    .replace(/\{\{brandName\}\}/g, brand.name)
    .replace(/\{\{brandShortName\}\}/g, brand.shortName)
    .replace(/\{\{brandTagline\}\}/g, brand.tagline)
    .replace(/\{\{supportEmail\}\}/g, brand.supportEmail)
    .replace(/\{\{copyright\}\}/g, brand.copyright);
}

module.exports = {
  FRONTEND_ROOT,
  PRODUCT,
  syncBrandAssets,
  buildThemeCss,
  toBrandConfig,
  applyBrandTokens,
};
