/**
 * Shared brand.env parser — mirrors alonix-idp-frontend/vite.config.ts conventions.
 */
const fs = require('fs');
const path = require('path');

const FRONTEND_ROOT = path.resolve(__dirname, '..', '..');
const BASELINE_BRAND = '1glance';

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const result = {};
  for (const line of fs.readFileSync(filePath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    result[key] = value;
  }
  return result;
}

function resolveBrandSlug() {
  return (
    process.env.DOCUSAURUS_BRAND?.trim() ||
    process.env.VITE_BRAND_MODE?.trim() ||
    'findoutai'
  );
}

function loadBrandEnv(slug) {
  const brandPath = path.join(FRONTEND_ROOT, 'brands', slug, 'brand.env');
  if (!fs.existsSync(brandPath)) {
    throw new Error(
      `Brand not found: brands/${slug}/brand.env — set DOCUSAURUS_BRAND or add the brand folder.`
    );
  }
  return parseEnvFile(brandPath);
}

function pickFaviconFile(files) {
  const priority = ['.png', '.ico', '.webp', '.svg'];
  for (const ext of priority) {
    const match = files.find((f) => f.startsWith('favicon.') && f.endsWith(ext));
    if (match) return match;
  }
  return files.find((f) => f.startsWith('favicon.'));
}

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, {recursive: true});
  for (const file of fs.readdirSync(src)) {
    if (file === '.DS_Store') continue;
    fs.copyFileSync(path.join(src, file), path.join(dest, file));
  }
}

function syncBrandAssets(slug, destDir) {
  if (fs.existsSync(destDir)) {
    fs.rmSync(destDir, {recursive: true, force: true});
  }
  fs.mkdirSync(destDir, {recursive: true});

  const baselineAssets = path.join(FRONTEND_ROOT, 'brands', BASELINE_BRAND, 'assets');
  copyDir(baselineAssets, destDir);

  if (slug !== BASELINE_BRAND) {
    const brandAssets = path.join(FRONTEND_ROOT, 'brands', slug, 'assets');
    copyDir(brandAssets, destDir);
  }
}

function resolveLogoPath(brandStaticDir) {
  const candidates = ['logo.png', 'logo.svg', 'logo.webp', 'logo-icon.png'];
  for (const file of candidates) {
    if (fs.existsSync(path.join(brandStaticDir, file))) return `brand/${file}`;
  }
  return 'img/logo.svg';
}

function resolveFaviconPath(brandStaticDir) {
  const files = fs.existsSync(brandStaticDir) ? fs.readdirSync(brandStaticDir) : [];
  const favicon = pickFaviconFile(files);
  return favicon ? `brand/${favicon}` : 'img/logo.svg';
}

function hexToRgb(hex) {
  const normalized = hex.replace('#', '');
  const full =
    normalized.length === 3
      ? normalized
          .split('')
          .map((c) => c + c)
          .join('')
      : normalized;
  const num = parseInt(full, 16);
  return {
    r: (num >> 16) & 255,
    g: (num >> 8) & 255,
    b: num & 255,
  };
}

function shadeHex(hex, amount) {
  const {r, g, b} = hexToRgb(hex);
  const channels = [r, g, b].map((channel) => {
    if (amount >= 0) {
      return Math.max(0, Math.min(255, Math.round(channel + (255 - channel) * amount)));
    }
    return Math.max(0, Math.min(255, Math.round(channel * (1 - Math.abs(amount)))));
  });
  return `#${channels.map((c) => c.toString(16).padStart(2, '0')).join('')}`;
}

function buildThemeCss(brand) {
  const light = brand.primaryLight;
  const dark = brand.primaryDark;
  return `/* Generated by scripts/sync-brand.js — do not edit */
:root {
  --ifm-color-primary: ${light};
  --ifm-color-primary-dark: ${shadeHex(light, -0.12)};
  --ifm-color-primary-darker: ${shadeHex(light, -0.2)};
  --ifm-color-primary-darkest: ${shadeHex(light, -0.32)};
  --ifm-color-primary-light: ${shadeHex(light, 0.12)};
  --ifm-color-primary-lighter: ${shadeHex(light, 0.24)};
  --ifm-color-primary-lightest: ${shadeHex(light, 0.36)};
  --docusaurus-highlighted-code-line-bg: rgba(${hexToRgb(light).r}, ${hexToRgb(light).g}, ${hexToRgb(light).b}, 0.1);
}

[data-theme='dark'] {
  --ifm-color-primary: ${dark};
  --ifm-color-primary-dark: ${shadeHex(dark, -0.1)};
  --ifm-color-primary-darker: ${shadeHex(dark, -0.18)};
  --ifm-color-primary-darkest: ${shadeHex(dark, -0.28)};
  --ifm-color-primary-light: ${shadeHex(dark, 0.1)};
  --ifm-color-primary-lighter: ${shadeHex(dark, 0.2)};
  --ifm-color-primary-lightest: ${shadeHex(dark, 0.3)};
}

.hero--primary {
  --ifm-hero-background-color: linear-gradient(
    135deg,
    ${shadeHex(light, -0.32)} 0%,
    ${light} 50%,
    ${shadeHex(light, 0.12)} 100%
  );
  --ifm-hero-text-color: #ffffff;
}
`;
}

function toBrandConfig(slug, env, brandStaticDir) {
  const optional = (key, fallback) => env[key] || fallback;
  return {
    slug,
    name: optional('VITE_BRAND_NAME', 'FindoutAI'),
    shortName: optional('VITE_BRAND_SHORT_NAME', 'FA'),
    tagline: optional(
      'VITE_BRAND_TAGLINE',
      'AI-Powered Document Intelligence for Every Enterprise'
    ),
    copyright: optional('VITE_BRAND_COPYRIGHT', 'FindoutAI Technologies Inc.'),
    supportEmail: optional('VITE_BRAND_SUPPORT_EMAIL', 'support@findoutai.com'),
    salesEmail: optional('VITE_BRAND_SALES_EMAIL', 'sales@findoutai.com'),
    websiteUrl: optional('VITE_BRAND_WEBSITE_URL', 'https://findoutai.com'),
    privacyUrl: optional('VITE_BRAND_PRIVACY_URL', 'https://findoutai.com/privacy'),
    termsUrl: optional('VITE_BRAND_TERMS_URL', 'https://findoutai.com/terms'),
    primaryLight: optional('VITE_BRAND_PRIMARY_LIGHT', '#7C3AED'),
    primaryDark: optional('VITE_BRAND_PRIMARY_DARK', '#C4B5FD'),
    logoPath: resolveLogoPath(brandStaticDir),
    faviconPath: resolveFaviconPath(brandStaticDir),
    helpCenterTitle: `${optional('VITE_BRAND_NAME', 'FindoutAI')} Help Center`,
    navbarTitle: `${optional('VITE_BRAND_SHORT_NAME', 'FA')} Help`,
  };
}

function applyBrandTokens(text, brand) {
  return text
    .replace(/\{\{brandName\}\}/g, brand.name)
    .replace(/\{\{brandShortName\}\}/g, brand.shortName)
    .replace(/\{\{brandTagline\}\}/g, brand.tagline)
    .replace(/\{\{supportEmail\}\}/g, brand.supportEmail)
    .replace(/\{\{copyright\}\}/g, brand.copyright);
}

module.exports = {
  FRONTEND_ROOT,
  BASELINE_BRAND,
  parseEnvFile,
  resolveBrandSlug,
  loadBrandEnv,
  syncBrandAssets,
  buildThemeCss,
  toBrandConfig,
  applyBrandTokens,
};
